'\" t
.\"     Title: system-config-printer-applet
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 24 Nov 2010
.\"    Manual: Man pages
.\"    Source: system-config-printer
.\"  Language: English
.\"
.TH "SYSTEM\-CONFIG\-PRIN" "1" "24 Nov 2010" "system-config-printer" "Man pages"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
system-config-printer-applet \- print job manager
.SH "SYNOPSIS"
.HP \w'\fBsystem\-config\-printer\-applet\fR\ 'u
\fBsystem\-config\-printer\-applet\fR [\-\-help] [\-\-version] [\-\-debug]
.SH "DESCRIPTION"
.PP
\fBsystem\-config\-printer\-applet\fR
is a print job manager for CUPS\&. Normally it will display a printer icon in the notification area, greyed out when there are no print jobs for the current user\&. Clicking on the icon displays a simple print job manager for cancelling or reprinting jobs\&.
.PP
To save memory, the applet waits first of all until the user has printed a job before putting the icon in the notification area\&. To invoke the print job manager before a job has been printed, run the applet with the
\fB\-\-no\-tray\-icon\fR
option: a desktop file is provided for this, so that it should appear in the system menu\&.
.PP
As well as displaying a printer icon in the notification area, the applet also provides a D\-BUS server for the com\&.redhat\&.PrintDriverSelection interface, to help configure a new printer when it is plugged in\&.
.SH "OPTIONS"
.PP
\fB\-\-help\fR
.RS 4
Display a short usage message\&.
.RE
.PP
\fB\-\-version\fR
.RS 4
Display the version of the applet\&.
.RE
.PP
\fB\-\-debug\fR
.RS 4
Show debugging information\&.
.RE
.SH "AUTHOR"
.PP
\fBTim Waugh\fR <\&twaugh@redhat.com\&>
.RS 4
Author.
.RE
